repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - "--args=--lockfile=false"
      - id: terraform_tflint
      - id: terraform_tfsec
